repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-submodules
      - id: name-tests-test
      - id: trailing-whitespace
ci:
  autofix_commit_msg: "style: auto fixes from pre-commit hooks"
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: "ci(pre-commit): auto-update hooks"
  autoupdate_schedule: weekly
  skip: [ ]
  submodules: false
