name: Bumping

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  bump:
    name: Version bump

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3
        with:
          enable-cache: true

      - name: Get current version
        id: old_version
        run: echo "old_version=$(uv version --short)" >> $GITHUB_ENV

      - name: Bump version
        run: uv version --bump {% raw %}${{ github.event.inputs.bump-type }}{% endraw %}

      - name: Get new version
        id: new_version
        run: echo "new_version=$(uv version --short)" >> $GITHUB_ENV

      - name: Commit, tag, and push changes
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          message: {% raw %}"chore: bump ${{ env.old_version }} → ${{ env.new_version }}"{% endraw %}
          tag: {% raw %}"v${{ env.new_version }}"{% endraw %}
