name: Bump version

on:
  workflow_dispatch:
    inputs:
      bump-type:
        description: 'Bump type'
        required: true
        default: 'patch'
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  bump:
    name: Bump version

    runs-on: ubuntu-latest

    steps:
      - name: Bump version
        uses: callowayproject/bump-my-version@574c65d01d92f35f58294e9e9296811d75410401 # v1.2.1
        env:
          BUMPVERSION_TAG: "true"
        with:
          args: ${{ inputs.bump-type }}
