[project]
name = "{{cookiecutter.project_slug}}"
version = "{{cookiecutter.first_version}}"
description = "{{cookiecutter.description}}"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[build-system]
requires = ["uv_build>=0.8.3,<0.9.0"]
build-backend = "uv_build"
